apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: audit-logs-runtime
  namespace: fcs-audit-logs
spec:
  infisicalAuthRef:
    name: fcs-platform-auth
    namespace: infisical-operator-system
  syncOptions:
    refreshInterval: 5m
    instantUpdates: false
  sources:
    - projectSlug: fcs-platform-dd-uk
      environmentSlug: prod
      secretPath: /platform
  targets:
    - name: audit-logs-runtime
      namespace: fcs-audit-logs
      kind: Secret
      creationPolicy: Owner
      template:
        engineVersion: v1
        data:
          MongoDbSettings__ConnectionString: mongodb://mongodb-service.fcs-infra.svc.cluster.local:27017
